version: 2.1
jobs: 
  pytorch-transformer:
    working_directory: ~/pytorch-transformer
    docker:
      - image: circleci/python:3.6
    steps:
      - run: |
          git clone https://github.com/huggingface/pytorch-transformers.git $(pwd)
      - run: |
          sed -i 's/name="pytorch_transformers"/name="pytorch_transformers_pvt_nightly"/g' setup.py
          sed -i -r 's/version="(.+?)"/version="\1.dev'`date -u "+%Y%m%d%H%M"`'"/g' setup.py
      - run: |
          pip install --user -U pip wheel twine
          python setup.py sdist bdist_wheel
      - run: |
          twine upload dist/*
  allennlp:
    working_directory: ~/allennlp
    docker:
      - image: circleci/python:3.6
    steps:
      - run: |
          git clone https://github.com/allenai/allennlp.git $(pwd)
      - run: |
          sed -i "s/name='allennlp'/name='allennlp_pvt_nightly'/g" setup.py
          sed -i -r 's/version=(.+?),/version=\1.split("-")[0] + ".dev'`date -u "+%Y%m%d%H%M"`'",/g' setup.py
      - run: |
          pip install --user -U pip wheel twine
          python setup.py sdist bdist_wheel
      - run: |
          twine upload dist/*
workflows:
  version: 2
  every-hour:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - pytorch-transformer
      - allennlp
  on-change:
    jobs:
      - pytorch-transformer
      - allennlp